# @package _global_
defaults:
  - /vit_pretrain
  - /model/braindino_vit_s@model
  - /hardware/1node4gpus@hardware
  - _self_

task: PT902_FOMO300K_HF
root: lesion_impossible
stem: pretrain

# Used to reconnect the source run’s logging information.
checkpoint_run_id: null

training:
  # This is what actually restores the student, teacher, centers,
  # optimizer, scheduler and global step.
  resume_ckpt: null