_pretrain_net:
  _target_: asparagus.modules.networks.braindino_vit.${model.pretrain_net}
  grid_size: ${model.grid_size}
  patch_kernel_size: ${model.patch_kernel_size}
  window_size: ${model.window_size}
  summary_grid_size: ${model.summary_grid_size}
  init_sigma_mm: ${model.init_sigma_mm}
  learn_sigma: ${model.learn_sigma}
  cls_projection_dim: ${model.cls_projection_dim}
  patch_projection_dim: ${model.patch_projection_dim}

_seg_net:
  _target_: asparagus.modules.networks.vit_task_model.${model.seg_net}
  grid_size: ${model.grid_size}
  patch_kernel_size: ${model.patch_kernel_size}
  window_size: ${model.window_size}
  summary_grid_size: ${model.summary_grid_size}
  init_sigma_mm: ${model.init_sigma_mm}
  learn_sigma: ${model.learn_sigma}

_cls_net:
  _target_: asparagus.modules.networks.vit_task_model.${model.cls_net}
  grid_size: ${model.grid_size}
  patch_kernel_size: ${model.patch_kernel_size}
  window_size: ${model.window_size}
  summary_grid_size: ${model.summary_grid_size}
  init_sigma_mm: ${model.init_sigma_mm}
  learn_sigma: ${model.learn_sigma}

_reg_net:
  _target_: asparagus.modules.networks.vit_task_model.${model.reg_net}
  grid_size: ${model.grid_size}
  patch_kernel_size: ${model.patch_kernel_size}
  window_size: ${model.window_size}
  summary_grid_size: ${model.summary_grid_size}
  init_sigma_mm: ${model.init_sigma_mm}
  learn_sigma: ${model.learn_sigma}

_plugin_seg_net:
  _target_: asparagus.modules.networks.vit_task_model.${model.plugin_seg_net}
  dimensions: ${model.dimensions}

recovery_ckpt_every_n_optimizer_steps: 2000
snapshot_ckpt_every_n_optimizer_steps: 10000

pretrain_optim: AdamW
pretrain_lr: 2.0e-4
weight_decay: 0.04
warmup_ratio: 0.05
cosine_period_ratio: 1.0
minimum_lr: 1.0e-6
ckpt_every_n_epoch: 5

train_optim: SGD
train_lr: 1e-2
nesterov: True
momentum: 0.99

finetune_optim: AdamW
finetune_lr: 1e-4
