_pretrain_net:
  _target_: asparagus.modules.networks.braindino_vit.${model.pretrain_net}
  grid_size: ${model.grid_size}
  patch_kernel_size: ${model.patch_kernel_size}
  window_size: ${model.window_size}
  summary_grid_size: ${model.summary_grid_size}
  init_sigma_mm: ${model.init_sigma_mm}
  learn_sigma: ${model.learn_sigma}
  cls_projection_dim: ${model.cls_projection_dim}
  patch_projection_dim: ${model.patch_projection_dim}

_seg_net:
  _target_: asparagus.modules.networks.vit_task_model.${model.seg_net}
  grid_size: ${model.grid_size}
  patch_kernel_size: ${model.patch_kernel_size}
  window_size: ${model.window_size}
  summary_grid_size: ${model.summary_grid_size}
  init_sigma_mm: ${model.init_sigma_mm}
  learn_sigma: ${model.learn_sigma}
  freeze_backbone: ${model.freeze_backbone}

_cls_net:
  _target_: asparagus.modules.networks.vit_task_model.${model.cls_net}
  grid_size: ${model.grid_size}
  patch_kernel_size: ${model.patch_kernel_size}
  window_size: ${model.window_size}
  summary_grid_size: ${model.summary_grid_size}
  init_sigma_mm: ${model.init_sigma_mm}
  learn_sigma: ${model.learn_sigma}
  hidden_dim: ${model.cls_hidden_dim}
  dropout: ${model.cls_dropout}
  top_k_fraction: ${model.cls_top_k_fraction}
  min_top_k: ${model.cls_min_top_k}
  token_logit_weight: ${model.cls_token_logit_weight}
  freeze_backbone: ${model.freeze_backbone}

_reg_net:
  _target_: asparagus.modules.networks.vit_task_model.${model.reg_net}
  grid_size: ${model.grid_size}
  patch_kernel_size: ${model.patch_kernel_size}
  window_size: ${model.window_size}
  summary_grid_size: ${model.summary_grid_size}
  init_sigma_mm: ${model.init_sigma_mm}
  learn_sigma: ${model.learn_sigma}
  freeze_backbone: ${model.freeze_backbone}

_plugin_seg_net:
  _target_: asparagus.modules.networks.vit_task_model.${model.plugin_seg_net}
  dimensions: ${model.dimensions}
