defaults:
  - core/braindino_vit@

dimensions: 3D

pretrain_net: pretrain_braindino_vit_b
seg_net: task_vit_b_seg
cls_net: task_vit_b_cls
reg_net: task_vit_b_reg

patch_kernel_size: 9
patch_stride: 8
patch_padding: 4

init_sigma_mm: 4.0
learn_sigma: true

cls_projection_dim: 65536
patch_projection_dim: 8192

plugin_seg_net:
plugin_seg_train_n_last_params:
